### ISSUE TITLE
Instructions (text)

### ISSUE THREAD

**Issue by devanteweary** [Emilien-Lambert/Unraid-VM-Backup-Plugin-Restoration-Script#5]
OK everyone, here are text instructions:
------------------------------------------------------------------

Open Unraid console.

Enter the following commands:
- cd /mnt/user/SHARE NAME/BACKUP FOLDER
- git clone https://github.com/Emilien-Lambert/Unraid-VM-Backup-Plugin-Restoration-Script.git
- This will clone the script to your backup folder.

Enter the following commands:
- cd Unraid-VM-Backup-Plugin-Restoration-Script
- chmod +x vm_backup_restoration.sh
- ./vm_backup_restoration.sh
- This will begin the script.

Do the following:
- Delete the VM you want to restore. Select Remove VM & Disks.
- Shut down all other VMs.
- Make sure the VM service is ENABLED/ON in Settings > VM Manager.

Enter the path of VM backups.
- Example: /mnt/user/SHARE NAME/BACKUP FOLDER/VMs

Enter name of VM you wish to restore.
- This will be the name of the folder of the VM you want to restore.
- Example: Ubuntu

Enter the date of the backup you want restored.
- For example, if the filename of the VM is 20220124_0300_Ubuntu.xml
- Just enter 20220124_0300

The restoration process could take several minutes.
Once complete, stop your Unraid storage array and start it again.

Your newly restored VM will show up.

------------------------------------------------------------------

Feel free to copy these to your description, Emilien.
🤙

**Comment by Emilien-Lambert** [comment]
Thx [devanteweary](https://github.com/devanteweary) it's push

**Comment by devanteweary** [comment]
> Thx [devanteweary](https://github.com/devanteweary) it's push

Hey I edited the instructions because the arrow brackets were messing it up.
It should be fixed now.
